import type { VerticalConfig } from '@/lib/intent/vertical-config'

/**
 * IVIS catalog — Indian Vertical Intelligence System. Each entry is a
 * specialist planner's worth of knowledge as data. Add an industry by
 * adding one object here; the detector and router pick it up automatically.
 */
export const VERTICALS: VerticalConfig[] = [
  // ── Professional Services ──────────────────────────────────
  {
    type: 'LAW_FIRM',
    label: 'Law Firm',
    category: 'Professional Services',
    typePhrases: ['law firm', 'legal services', 'advocates', 'law office', 'chambers'],
    strong: ['lawyer', 'advocate', 'attorney', 'litigation', 'legal', 'counsel'],
    weak: ['corporate law', 'practice areas', 'bar', 'court', 'dispute', 'arbitration', 'compliance'],
    design: {
      direction: 'Premium, trustworthy, restrained — authority through gravitas',
      palette: ['deep navy / charcoal', 'warm off-white', 'one muted gold or oxblood accent'],
      display: 'High-trust serif', body: 'Clean serif or grotesk', mood: 'Authoritative, discreet, established',
      motion: 'Minimal — slow, deliberate reveals only',
    },
    sections: [
      { name: 'Hero', job: 'State the firm’s standing and areas of strength' },
      { name: 'Practice Areas', job: 'Show the legal domains they win in' },
      { name: 'About the Firm', job: 'Establish history, values, credibility' },
      { name: 'Partners & Team', job: 'Faces, credentials, bar standing' },
      { name: 'Testimonials', job: 'Discreet proof from clients/peers' },
      { name: 'Consultation', job: 'Convert a serious enquiry' },
      { name: 'Contact', job: 'Offices, hours, direct lines' },
    ],
    primaryCta: { label: 'Book a Consultation', action: '#consultation' },
    secondaryCta: { label: 'Speak with an Advocate', action: '#contact' },
    features: ['Consultation booking', 'Practice-area pages', 'Partner profiles', 'Office locations'],
    seo: { titlePattern: '{name} — Advocates & Legal Consultants, {city}', focus: 'practice area + city intent' },
    antiPatterns: ['No playful colour or motion', 'No stocky "teamwork" photos', 'Never read as a startup'],
  },
  {
    type: 'CA_FIRM',
    label: 'Chartered Accountancy Firm',
    category: 'Professional Services',
    typePhrases: ['chartered accountant', 'ca firm', 'accounting firm', 'tax consultant', 'audit firm'],
    strong: ['ca', 'gst', 'audit', 'taxation', 'compliance', 'bookkeeping'],
    weak: ['itr', 'roc', 'tds', 'income tax', 'financial', 'statutory', 'filing'],
    design: {
      direction: 'Professional, corporate, immaculately clean — precision as trust',
      palette: ['corporate blue', 'white / light grey', 'a single confident accent'],
      display: 'Clean grotesk', body: 'Readable sans', mood: 'Reliable, precise, calm',
      motion: 'Subtle, businesslike',
    },
    sections: [
      { name: 'Hero', job: 'Lead with clarity on what they handle' },
      { name: 'Services', job: 'GST, audit, tax, ROC, advisory — scannable' },
      { name: 'Industries', job: 'Show sector experience' },
      { name: 'Partners', job: 'Credentials and membership numbers' },
      { name: 'Testimonials', job: 'Trust from businesses served' },
      { name: 'FAQs', job: 'Answer common compliance questions' },
      { name: 'Contact', job: 'Easy way to start' },
    ],
    primaryCta: { label: 'Book a Consultation', action: '#contact' },
    secondaryCta: { label: 'Talk to a CA', action: '#contact' },
    features: ['Service catalogue', 'Compliance FAQs', 'Industry pages', 'Enquiry form'],
    seo: { titlePattern: '{name} — Chartered Accountants, {city}', focus: 'GST/tax/audit + city' },
    antiPatterns: ['No flashy gradients', 'No vague jargon without service clarity', 'Never feel like an agency'],
  },
  {
    type: 'CONSULTING',
    label: 'Consulting Firm',
    category: 'Professional Services',
    typePhrases: ['consulting firm', 'business consulting', 'advisory firm', 'management consulting'],
    strong: ['consultant', 'advisory', 'strategy', 'consulting'],
    weak: ['transformation', 'operations', 'process', 'roadmap', 'engagement'],
    design: {
      direction: 'Confident, structured, evidence-led', palette: ['ink', 'warm neutral', 'one sharp accent'],
      display: 'Modern serif or strong grotesk', body: 'Clean sans', mood: 'Smart, credible, senior',
      motion: 'Purposeful reveals',
    },
    sections: [
      { name: 'Hero', job: 'State the outcome they deliver' },
      { name: 'Services', job: 'The advisory offerings' },
      { name: 'Case Studies', job: 'Proof via real engagements' },
      { name: 'Process', job: 'How an engagement runs' },
      { name: 'Clients', job: 'Logos / sectors served' },
      { name: 'Testimonials', job: 'Senior, specific endorsements' },
      { name: 'Contact', job: 'Start a conversation' },
    ],
    primaryCta: { label: 'Start a Conversation', action: '#contact' },
    features: ['Case studies', 'Process timeline', 'Client logos'],
    seo: { titlePattern: '{name} — Business & Strategy Consulting', focus: 'advisory + sector' },
    antiPatterns: ['No template feel', 'No vague buzzwords without proof'],
  },
  // ── Creative ───────────────────────────────────────────────
  {
    type: 'DESIGN_AGENCY',
    label: 'Design Agency',
    category: 'Creative',
    typePhrases: ['design agency', 'design studio', 'branding agency', 'ui ux studio', 'creative agency'],
    strong: ['branding', 'design', 'ux', 'ui', 'creative'],
    weak: ['identity', 'portfolio', 'studio', 'visual', 'experience', 'art direction'],
    design: {
      direction: 'Bold, experimental, motion-forward — the work is the pitch',
      palette: ['expressive — high contrast base + a vivid signature'], display: 'Distinctive display with character',
      body: 'Clean grotesk', mono: 'Mono for captions', mood: 'Confident, playful, sharp', motion: 'Rich, choreographed, tasteful',
    },
    sections: [
      { name: 'Hero', job: 'A bold statement of point of view' },
      { name: 'Services', job: 'What they make' },
      { name: 'Portfolio', job: 'Show the work, large and proud' },
      { name: 'Case Studies', job: 'Depth on signature projects' },
      { name: 'Process', job: 'How they think' },
      { name: 'Testimonials', job: 'Client love' },
      { name: 'Contact', job: 'Start a project' },
    ],
    primaryCta: { label: 'Start a Project', action: '#contact' },
    secondaryCta: { label: 'See the Work', action: '#portfolio' },
    features: ['Portfolio grid', 'Case studies', 'Motion-rich hero'],
    seo: { titlePattern: '{name} — Design & Branding Studio', focus: 'branding/UX + city' },
    antiPatterns: ['No corporate stiffness', 'No generic stock', 'Never under-design it'],
  },
  {
    type: 'MARKETING_AGENCY',
    label: 'Marketing Agency',
    category: 'Creative',
    typePhrases: ['marketing agency', 'digital marketing', 'performance marketing', 'seo agency', 'social media agency'],
    strong: ['marketing', 'seo', 'ads', 'campaigns', 'growth'],
    weak: ['social media', 'ppc', 'leads', 'roi', 'funnel', 'content'],
    design: {
      direction: 'Energetic, results-forward, conversion-engineered', palette: ['vivid accent', 'dark or bright base', 'signal colour for metrics'],
      display: 'Punchy grotesk', body: 'Clean sans', mood: 'Driven, confident, data-proud', motion: 'Snappy, attention-guiding',
    },
    sections: [
      { name: 'Hero', job: 'Lead with the result they drive' },
      { name: 'Services', job: 'Channels & offerings' },
      { name: 'Case Studies', job: 'Numbers that prove it' },
      { name: 'Clients', job: 'Brands served' },
      { name: 'Testimonials', job: 'Outcome-led quotes' },
      { name: 'Contact', job: 'Get a proposal' },
    ],
    primaryCta: { label: 'Get a Free Audit', action: '#contact' },
    features: ['Result metrics', 'Case studies', 'Client logos'],
    seo: { titlePattern: '{name} — Digital Marketing Agency', focus: 'service + city + results' },
    antiPatterns: ['No vague promises without numbers', 'No clutter'],
  },
  // ── Food & Hospitality ─────────────────────────────────────
  {
    type: 'CAFE',
    label: 'Café / Coffee House',
    category: 'Food & Hospitality',
    typePhrases: ['café', 'cafe', 'coffee shop', 'coffee house', 'espresso bar', 'roastery'],
    strong: ['coffee', 'espresso', 'latte', 'barista', 'roast', 'pastry', 'brunch'],
    weak: ['menu', 'beans', 'cozy', 'breakfast', 'seating', 'hours'],
    design: {
      direction: 'Warm, tactile, editorial-rustic — like a well-art-directed menu',
      palette: ['warm espresso brown', 'cream / oat', 'one ripe accent (terracotta or sage)'],
      display: 'Characterful serif or warm humanist', body: 'Clean humanist sans', mood: 'Inviting, sensory, unhurried',
      motion: 'Slow fades, grain texture, parallax on food imagery',
    },
    sections: [
      { name: 'Arrival', job: 'Make the room feel inviting in one frame' },
      { name: 'Signature Menu', job: 'Show the craft, not a list' },
      { name: 'Full Menu', job: 'Let people browse' },
      { name: 'Our Story', job: 'Warmth and trust in the people' },
      { name: 'Gallery', job: 'Sell the atmosphere' },
      { name: 'Reviews', job: 'Social proof' },
      { name: 'Visit', job: 'Map, hours, reservation' },
    ],
    primaryCta: { label: 'Reserve a Table', action: '#visit' },
    secondaryCta: { label: 'See the Menu', action: '#full-menu' },
    features: ['Reservation CTA', 'Opening hours', 'Map embed', 'Menu cards', 'Food photography'],
    seo: { titlePattern: '{name} — Café in {city}', focus: 'local + dish-led keywords' },
    antiPatterns: ['No SaaS feature grids', 'No "Get started" CTA', 'No pricing tiers', 'Never cold or corporate'],
  },
  {
    type: 'RESTAURANT',
    label: 'Restaurant',
    category: 'Food & Hospitality',
    typePhrases: ['restaurant', 'fine dining', 'dining', 'eatery', 'bistro', 'kitchen & bar'],
    strong: ['restaurant', 'dining', 'chef', 'cuisine', 'menu'],
    weak: ['reservation', 'table', 'tasting', 'dishes', 'bar', 'food'],
    design: {
      direction: 'Cinematic, appetite-first, atmospheric', palette: ['deep warm base', 'candle-gold accent', 'rich neutrals'],
      display: 'Elegant serif', body: 'Refined sans', mood: 'Indulgent, intimate, crafted', motion: 'Slow cinematic reveals',
    },
    sections: [
      { name: 'Hero', job: 'A mouth-watering signature frame' },
      { name: 'Menu', job: 'The dishes, art-directed' },
      { name: 'The Chef', job: 'Story and credibility behind the food' },
      { name: 'Gallery', job: 'Room, plating, atmosphere' },
      { name: 'Reservations', job: 'Book a table' },
      { name: 'Reviews', job: 'Diner proof' },
      { name: 'Contact', job: 'Location & hours' },
    ],
    primaryCta: { label: 'Reserve a Table', action: '#reservations' },
    features: ['Reservation system', 'Menu', 'Chef story', 'Gallery', 'Map'],
    seo: { titlePattern: '{name} — {cuisine} Restaurant in {city}', focus: 'cuisine + city' },
    antiPatterns: ['No SaaS/corporate layout', 'No "features" grid', 'Never look like a template'],
  },
  {
    type: 'HOTEL',
    label: 'Hotel',
    category: 'Food & Hospitality',
    typePhrases: ['hotel', 'resort', 'boutique hotel', 'stay', 'guest house'],
    strong: ['hotel', 'rooms', 'suites', 'resort', 'booking', 'stay'],
    weak: ['amenities', 'spa', 'check-in', 'hospitality', 'guests', 'rates'],
    design: {
      direction: 'Luxurious, serene, photography-led — sell the escape', palette: ['warm neutral / sand', 'deep green or ink', 'gold accent'],
      display: 'Elegant serif', body: 'Light sans', mood: 'Calm, premium, restful', motion: 'Gentle, immersive',
    },
    sections: [
      { name: 'Hero', job: 'The dream of the stay in one frame' },
      { name: 'Rooms & Suites', job: 'Show the spaces and rates' },
      { name: 'Amenities', job: 'Spa, dining, pool — the experience' },
      { name: 'Gallery', job: 'Immerse in the property' },
      { name: 'Booking', job: 'Convert to a reservation' },
      { name: 'Location', job: 'Where it is, what’s nearby' },
      { name: 'Contact', job: 'Reach the front desk' },
    ],
    primaryCta: { label: 'Check Availability', action: '#booking' },
    secondaryCta: { label: 'Explore Rooms', action: '#rooms-suites' },
    features: ['Booking / availability', 'Room types', 'Amenities', 'Gallery', 'Map'],
    seo: { titlePattern: '{name} — Hotel in {city}', focus: 'stay + location + amenities' },
    antiPatterns: ['No clutter', 'No corporate tone', 'Never cheap-looking imagery'],
  },
  // ── Healthcare ─────────────────────────────────────────────
  {
    type: 'HOSPITAL',
    label: 'Hospital',
    category: 'Healthcare',
    typePhrases: ['hospital', 'multispecialty', 'medical centre', 'healthcare centre', 'nursing home'],
    strong: ['hospital', 'departments', 'doctors', 'emergency', 'patients', 'medical'],
    weak: ['appointment', 'treatment', 'specialities', 'facilities', 'care', 'icu'],
    design: {
      direction: 'Trustworthy, clean, reassuring, highly accessible', palette: ['calm medical blue/teal', 'white', 'a warm human accent'],
      display: 'Friendly grotesk', body: 'Highly legible sans', mood: 'Safe, competent, caring', motion: 'Minimal, never anxious',
    },
    sections: [
      { name: 'Hero', job: 'Reassure and route quickly (emergency visible)' },
      { name: 'Departments', job: 'Specialities at a glance' },
      { name: 'Doctors', job: 'Credentialed specialists' },
      { name: 'Facilities', job: 'Infrastructure that builds confidence' },
      { name: 'Emergency', job: 'Number and directions, prominent' },
      { name: 'Appointment', job: 'Book a visit easily' },
      { name: 'Contact', job: 'Reach the hospital' },
    ],
    primaryCta: { label: 'Book an Appointment', action: '#appointment' },
    secondaryCta: { label: 'Emergency: Call Now', action: '#emergency' },
    features: ['Appointment booking', 'Emergency number', 'Department pages', 'Doctor profiles'],
    seo: { titlePattern: '{name} — Multispeciality Hospital in {city}', focus: 'speciality + city + emergency' },
    antiPatterns: ['No playful or trendy aesthetics', 'Never bury the emergency contact', 'No low-contrast text'],
  },
  {
    type: 'CLINIC',
    label: 'Clinic',
    category: 'Healthcare',
    typePhrases: ['clinic', 'polyclinic', 'health clinic', 'medical clinic'],
    strong: ['clinic', 'treatments', 'doctor', 'consultation'],
    weak: ['appointment', 'patients', 'care', 'opd', 'checkup'],
    design: {
      direction: 'Clean, warm, personal — a trusted local practice', palette: ['soft teal/green', 'white', 'warm accent'],
      display: 'Friendly grotesk', body: 'Legible sans', mood: 'Caring, approachable, safe', motion: 'Gentle',
    },
    sections: [
      { name: 'Hero', job: 'Warm, reassuring intro' },
      { name: 'Treatments', job: 'What they help with' },
      { name: 'Doctors', job: 'Who you’ll see' },
      { name: 'Testimonials', job: 'Patient trust' },
      { name: 'Appointment', job: 'Book a visit' },
      { name: 'Contact', job: 'Find & reach the clinic' },
    ],
    primaryCta: { label: 'Book an Appointment', action: '#appointment' },
    features: ['Appointment booking', 'Treatment list', 'Doctor profiles', 'Map'],
    seo: { titlePattern: '{name} — Clinic in {city}', focus: 'treatment + locality' },
    antiPatterns: ['No corporate coldness', 'No low contrast', 'Never hype'],
  },
  {
    type: 'DENTAL_CLINIC',
    label: 'Dental Clinic',
    category: 'Healthcare',
    typePhrases: ['dental clinic', 'dentist', 'dental care', 'orthodontist'],
    strong: ['dental', 'dentist', 'teeth', 'orthodontic'],
    weak: ['implants', 'braces', 'smile', 'whitening', 'appointment', 'rct'],
    design: {
      direction: 'Bright, clean, confidence-building (before/after led)', palette: ['fresh white/mint', 'clean blue', 'friendly accent'],
      display: 'Rounded friendly grotesk', body: 'Legible sans', mood: 'Fresh, friendly, reassuring', motion: 'Light',
    },
    sections: [
      { name: 'Hero', job: 'Friendly, confidence-first intro' },
      { name: 'Treatments', job: 'Implants, braces, whitening…' },
      { name: 'The Dentist', job: 'Credentials and warmth' },
      { name: 'Before & After', job: 'Visual proof of results' },
      { name: 'Testimonials', job: 'Patient confidence' },
      { name: 'Appointment', job: 'Book easily' },
    ],
    primaryCta: { label: 'Book an Appointment', action: '#appointment' },
    features: ['Before/after gallery', 'Treatment pages', 'Appointment booking'],
    seo: { titlePattern: '{name} — Dental Clinic in {city}', focus: 'treatment + locality' },
    antiPatterns: ['No clinical coldness', 'Never graphic/scary imagery'],
  },
  // ── Education ──────────────────────────────────────────────
  {
    type: 'COACHING',
    label: 'Coaching Institute',
    category: 'Education',
    typePhrases: ['coaching institute', 'coaching centre', 'tuition', 'academy', 'test prep'],
    strong: ['coaching', 'jee', 'neet', 'upsc', 'batch', 'faculty', 'results'],
    weak: ['students', 'courses', 'rank', 'admission', 'classes', 'exam'],
    design: {
      direction: 'Results-forward, trust-heavy, bright and motivating', palette: ['confident primary (blue/saffron)', 'white', 'success-green for results'],
      display: 'Strong grotesk', body: 'Legible sans', mood: 'Aspirational, credible, energetic', motion: 'Lively but focused',
    },
    sections: [
      { name: 'Hero', job: 'Lead with the promise + proof of ranks' },
      { name: 'Courses', job: 'Batches and programs' },
      { name: 'Faculty', job: 'The teachers who deliver results' },
      { name: 'Results', job: 'Toppers, ranks, selections — the hero proof' },
      { name: 'Testimonials', job: 'Student & parent trust' },
      { name: 'Gallery', job: 'Campus and classroom life' },
      { name: 'Contact', job: 'Enquire / enrol' },
    ],
    primaryCta: { label: 'Enrol Now', action: '#contact' },
    secondaryCta: { label: 'Download Brochure', action: '#courses' },
    features: ['Results showcase', 'Course/batch pages', 'Faculty profiles', 'Enquiry form'],
    seo: { titlePattern: '{name} — {exam} Coaching in {city}', focus: 'exam + city + results' },
    antiPatterns: ['Never hide results/ranks', 'No minimalist restraint that buries proof', 'No corporate tone'],
  },
  {
    type: 'SCHOOL',
    label: 'School',
    category: 'Education',
    typePhrases: ['school', 'cbse school', 'icse school', 'public school', 'vidyalaya'],
    strong: ['school', 'students', 'academics', 'admissions', 'curriculum'],
    weak: ['classes', 'campus', 'faculty', 'cbse', 'icse', 'co-curricular'],
    design: {
      direction: 'Warm, wholesome, trustworthy for parents', palette: ['friendly primary', 'white', 'warm secondary'],
      display: 'Approachable serif or grotesk', body: 'Legible sans', mood: 'Nurturing, credible, vibrant', motion: 'Gentle',
    },
    sections: [
      { name: 'Hero', job: 'The school’s ethos and warmth' },
      { name: 'About', job: 'Vision, values, leadership' },
      { name: 'Academics', job: 'Curriculum and approach' },
      { name: 'Facilities', job: 'Campus, labs, sports' },
      { name: 'Admissions', job: 'How and when to apply' },
      { name: 'Events', job: 'Life at the school' },
      { name: 'Contact', job: 'Reach the office' },
    ],
    primaryCta: { label: 'Enquire for Admission', action: '#admissions' },
    features: ['Admissions info', 'Academics', 'Facilities', 'Events'],
    seo: { titlePattern: '{name} — CBSE/ICSE School in {city}', focus: 'board + locality + admissions' },
    antiPatterns: ['No corporate coldness', 'Never trendy over trustworthy'],
  },
  // ── Real Estate ────────────────────────────────────────────
  {
    type: 'BUILDER',
    label: 'Builder / Developer',
    category: 'Real Estate',
    typePhrases: ['builder', 'real estate developer', 'construction company', 'township', 'realty'],
    strong: ['builder', 'project', 'apartments', 'flats', 'township', 'possession'],
    weak: ['amenities', 'floor plan', 'rera', 'bhk', 'construction', 'booking'],
    design: {
      direction: 'Aspirational, premium, photography & plan led', palette: ['architectural neutral', 'deep accent', 'gold for premium'],
      display: 'Elegant grotesk/serif', body: 'Clean sans', mood: 'Premium, aspirational, solid', motion: 'Cinematic property reveals',
    },
    sections: [
      { name: 'Hero', job: 'The flagship project, aspirational' },
      { name: 'Projects', job: 'Ongoing & completed developments' },
      { name: 'Amenities', job: 'Lifestyle the project offers' },
      { name: 'Gallery', job: 'Renders, site, sample flat' },
      { name: 'Floor Plans', job: 'Layouts and configurations' },
      { name: 'Contact', job: 'Enquire / site visit' },
    ],
    primaryCta: { label: 'Book a Site Visit', action: '#contact' },
    secondaryCta: { label: 'View Floor Plans', action: '#floor-plans' },
    features: ['Project pages', 'Floor plans', 'Amenities', 'RERA details', 'Enquiry form'],
    seo: { titlePattern: '{name} — {bhk} Apartments in {locality}', focus: 'project + locality + BHK' },
    antiPatterns: ['No cheap stock', 'Never omit RERA/location clarity', 'No clutter'],
  },
  {
    type: 'INTERIOR_DESIGNER',
    label: 'Interior Designer',
    category: 'Real Estate',
    typePhrases: ['interior designer', 'interior design', 'home interiors', 'interior studio'],
    strong: ['interior', 'interiors', 'decor', 'furnishing'],
    weak: ['modular', 'living', 'space', 'turnkey', 'renovation', 'design'],
    design: {
      direction: 'Editorial, tactile, photography-first — the rooms sell it', palette: ['warm neutral', 'rich material tones', 'one refined accent'],
      display: 'Elegant serif', body: 'Clean sans', mood: 'Refined, warm, crafted', motion: 'Smooth gallery reveals',
    },
    sections: [
      { name: 'Hero', job: 'A signature room, beautifully shot' },
      { name: 'Projects', job: 'Portfolio of spaces' },
      { name: 'Services', job: 'What they do, end to end' },
      { name: 'Process', job: 'How a project runs' },
      { name: 'Testimonials', job: 'Happy homeowners' },
      { name: 'Contact', job: 'Start a project' },
    ],
    primaryCta: { label: 'Book a Consultation', action: '#contact' },
    features: ['Project gallery', 'Services', 'Process'],
    seo: { titlePattern: '{name} — Interior Designers in {city}', focus: 'interiors + city' },
    antiPatterns: ['No clutter', 'Never under-photograph the work'],
  },
  // ── Retail ─────────────────────────────────────────────────
  {
    type: 'JEWELLERY_STORE',
    label: 'Jewellery Store',
    category: 'Retail',
    typePhrases: ['jewellery', 'jewelry', 'jeweller', 'gold shop', 'diamond store'],
    strong: ['jewellery', 'jewelry', 'gold', 'diamond', 'ornaments'],
    weak: ['bridal', 'collections', 'craftsmanship', 'silver', 'rings', 'necklace'],
    design: {
      direction: 'Opulent, heritage-luxury, product-as-hero', palette: ['deep maroon/black', 'gold', 'ivory'],
      display: 'High-contrast serif', body: 'Refined serif/sans', mood: 'Luxurious, heritage, celebratory', motion: 'Slow, jewel-lit reveals',
    },
    sections: [
      { name: 'Hero', job: 'A statement piece, lit like a jewel' },
      { name: 'Collections', job: 'Bridal, daily, festive ranges' },
      { name: 'Craftsmanship', job: 'The making and heritage' },
      { name: 'Gallery', job: 'Showcase pieces' },
      { name: 'Contact', job: 'Visit the showroom' },
    ],
    primaryCta: { label: 'Visit Showroom', action: '#contact' },
    secondaryCta: { label: 'Explore Collections', action: '#collections' },
    features: ['Collections', 'Craftsmanship story', 'Showroom info'],
    seo: { titlePattern: '{name} — Jewellers in {city}', focus: 'bridal/gold/diamond + city' },
    antiPatterns: ['No cheap or busy layout', 'Never flat product photos', 'No tech aesthetics'],
  },
  {
    type: 'FASHION_BOUTIQUE',
    label: 'Fashion Boutique',
    category: 'Retail',
    typePhrases: ['boutique', 'fashion boutique', 'clothing store', 'apparel brand', 'designer wear'],
    strong: ['boutique', 'fashion', 'collection', 'apparel', 'ethnic', 'couture'],
    weak: ['lookbook', 'outfits', 'styles', 'wear', 'designer', 'trends'],
    design: {
      direction: 'Editorial, lookbook-led, on-trend', palette: ['fashion-forward base', 'one statement hue', 'neutral support'],
      display: 'Stylish display serif', body: 'Clean sans', mood: 'Chic, expressive, current', motion: 'Editorial reveals',
    },
    sections: [
      { name: 'Hero', job: 'A campaign-grade fashion frame' },
      { name: 'Collections', job: 'Seasonal / category ranges' },
      { name: 'Lookbook', job: 'Styled, editorial imagery' },
      { name: 'Testimonials', job: 'Customer love' },
      { name: 'Contact', job: 'Visit / order' },
    ],
    primaryCta: { label: 'Shop the Collection', action: '#collections' },
    features: ['Collections', 'Lookbook', 'Store info'],
    seo: { titlePattern: '{name} — Fashion Boutique in {city}', focus: 'category + city' },
    antiPatterns: ['No corporate look', 'Never weak imagery'],
  },
  // ── Local MSME ─────────────────────────────────────────────
  {
    type: 'MANUFACTURING',
    label: 'Manufacturing Company',
    category: 'Local MSME',
    typePhrases: ['manufacturer', 'manufacturing company', 'factory', 'industrial', 'oem'],
    strong: ['manufacturing', 'manufacturer', 'products', 'factory', 'industrial', 'export'],
    weak: ['capabilities', 'infrastructure', 'machinery', 'capacity', 'iso', 'supply', 'oem'],
    design: {
      direction: 'Solid, industrial, capability-proud, B2B-credible', palette: ['steel grey / navy', 'white', 'safety-accent (orange/blue)'],
      display: 'Strong industrial grotesk', body: 'Clean sans', mood: 'Robust, reliable, capable', motion: 'Restrained, precise',
    },
    sections: [
      { name: 'Hero', job: 'What they make and for whom' },
      { name: 'Products', job: 'Product range / catalogue' },
      { name: 'Capabilities', job: 'Processes and quality systems' },
      { name: 'Industries', job: 'Sectors served' },
      { name: 'Infrastructure', job: 'Plant, capacity, certifications' },
      { name: 'Contact', job: 'Request a quote' },
    ],
    primaryCta: { label: 'Request a Quote', action: '#contact' },
    secondaryCta: { label: 'Download Catalogue', action: '#products' },
    features: ['Product catalogue', 'Capabilities', 'Certifications (ISO)', 'Enquiry/RFQ form'],
    seo: { titlePattern: '{name} — {product} Manufacturer in India', focus: 'product + manufacturer + B2B' },
    antiPatterns: ['No consumer-cute aesthetics', 'Never omit capability/certification proof', 'No fluff'],
  },
  {
    type: 'TRAVEL_AGENCY',
    label: 'Travel Agency',
    category: 'Local MSME',
    typePhrases: ['travel agency', 'tour operator', 'holiday packages', 'travel agent', 'tours and travels'],
    strong: ['travel', 'tours', 'packages', 'holidays', 'trips', 'destinations'],
    weak: ['itinerary', 'booking', 'honeymoon', 'visa', 'flights', 'getaway'],
    design: {
      direction: 'Wanderlust-led, photography-first, vivid', palette: ['sky/ocean tones', 'warm sand', 'vivid accent'],
      display: 'Friendly display', body: 'Clean sans', mood: 'Inspiring, joyful, trustworthy', motion: 'Immersive destination reveals',
    },
    sections: [
      { name: 'Hero', job: 'Sell the feeling of the trip' },
      { name: 'Packages', job: 'Curated holiday packages' },
      { name: 'Destinations', job: 'Where they take you' },
      { name: 'Testimonials', job: 'Happy travellers' },
      { name: 'Contact', job: 'Plan a trip' },
    ],
    primaryCta: { label: 'Plan My Trip', action: '#contact' },
    secondaryCta: { label: 'View Packages', action: '#packages' },
    features: ['Package listings', 'Destination pages', 'Enquiry form'],
    seo: { titlePattern: '{name} — Tours & Travels in {city}', focus: 'destination + package + city' },
    antiPatterns: ['No weak stock', 'No corporate dryness'],
  },
  {
    type: 'EVENT_MANAGEMENT',
    label: 'Event Management',
    category: 'Local MSME',
    typePhrases: ['event management', 'event planner', 'wedding planner', 'events company'],
    strong: ['events', 'wedding', 'planning', 'celebration'],
    weak: ['decor', 'venue', 'corporate event', 'gallery', 'occasion'],
    design: {
      direction: 'Celebratory, glamorous, gallery-led', palette: ['rich celebratory base', 'gold/blush accent', 'neutral support'],
      display: 'Elegant display', body: 'Clean sans', mood: 'Festive, premium, joyful', motion: 'Lush gallery reveals',
    },
    sections: [
      { name: 'Hero', job: 'A showstopping event frame' },
      { name: 'Services', job: 'Weddings, corporate, social' },
      { name: 'Events', job: 'Signature events delivered' },
      { name: 'Gallery', job: 'Proof of production quality' },
      { name: 'Testimonials', job: 'Delighted clients' },
      { name: 'Contact', job: 'Plan an event' },
    ],
    primaryCta: { label: 'Plan Your Event', action: '#contact' },
    features: ['Service list', 'Event gallery', 'Enquiry form'],
    seo: { titlePattern: '{name} — Event & Wedding Planners in {city}', focus: 'event type + city' },
    antiPatterns: ['No dull layout', 'Never under-show the gallery'],
  },
  // ── Technology ─────────────────────────────────────────────
  {
    type: 'SAAS',
    label: 'SaaS / Product Landing',
    category: 'Technology',
    typePhrases: ['saas', 'landing page', 'product landing', 'our app', 'our platform', 'b2b software', 'web app'],
    strong: ['saas', 'platform', 'product', 'api', 'dashboard', 'integration'],
    weak: ['features', 'pricing', 'signup', 'demo', 'workflow', 'automation', 'analytics'],
    design: {
      direction: 'Precise, modern-confident — Linear/Stripe register; product IS the proof',
      palette: ['near-neutral canvas', 'one product accent used surgically', 'signal colours for product UI'],
      display: 'Tight technical grotesk', body: 'Clean grotesk', mono: 'Mono for product/data labels', mood: 'Calm, exact, trustworthy',
      motion: 'Compositor-only reveals, magnetic CTA, a live product surface',
    },
    sections: [
      { name: 'Hero', job: 'State value + show the product in one frame' },
      { name: 'Logos', job: 'Borrow credibility fast' },
      { name: 'Features', job: 'The 3 things it actually does' },
      { name: 'Integrations', job: 'Fits your stack' },
      { name: 'Pricing', job: 'Make the decision easy' },
      { name: 'FAQ', job: 'Remove last objections' },
      { name: 'CTA', job: 'Single confident conversion' },
    ],
    primaryCta: { label: 'Start Free', action: '#cta' },
    secondaryCta: { label: 'Book a Demo', action: '#contact' },
    features: ['Feature sections', 'Pricing tiers', 'Integrations', 'Rendered product UI', 'FAQ'],
    seo: { titlePattern: '{name} — {one-line value}', focus: 'category + problem keywords' },
    antiPatterns: ['No food/menu/reservation anything', 'No "about me" voice', 'No decorative mesh-gradient filler'],
  },
  {
    type: 'STARTUP',
    label: 'Startup',
    category: 'Technology',
    typePhrases: ['startup', 'our startup', 'we are building', 'early stage'],
    strong: ['startup', 'problem', 'solution', 'mission', 'vision'],
    weak: ['team', 'roadmap', 'launch', 'beta', 'funding', 'traction'],
    design: {
      direction: 'Energetic, narrative-led, momentum-forward', palette: ['bold base', 'vivid accent', 'clean neutral'],
      display: 'Punchy grotesk', body: 'Clean sans', mood: 'Ambitious, fresh, credible', motion: 'Lively, purposeful',
    },
    sections: [
      { name: 'Hero', job: 'The mission in one confident line' },
      { name: 'Problem', job: 'The pain they attack' },
      { name: 'Solution', job: 'How they solve it' },
      { name: 'Features', job: 'What it does today' },
      { name: 'Team', job: 'Who is building it' },
      { name: 'Roadmap', job: 'Where it’s going' },
      { name: 'CTA', job: 'Join / get early access' },
    ],
    primaryCta: { label: 'Get Early Access', action: '#cta' },
    features: ['Problem/solution narrative', 'Team', 'Roadmap', 'Waitlist'],
    seo: { titlePattern: '{name} — {one-line pitch}', focus: 'problem + category' },
    antiPatterns: ['No corporate stiffness', 'No empty buzzwords'],
  },
  // ── General business ───────────────────────────────────────
  {
    type: 'COMPANY_WEBSITE',
    label: 'Company Website',
    category: 'General',
    typePhrases: ['company website', 'company profile', 'corporate website', 'about our company', 'our organisation'],
    strong: ['company', 'corporate', 'organisation', 'organization', 'enterprise'],
    weak: ['about us', 'services', 'team', 'mission', 'clients', 'industries'],
    design: {
      direction: 'Credible, clean, corporate-modern — trust through clarity', palette: ['confident corporate base', 'one accent', 'neutral support'],
      display: 'Modern grotesk', body: 'Clean sans', mood: 'Professional, established, clear', motion: 'Subtle, businesslike',
    },
    sections: [
      { name: 'Hero', job: 'What the company does and for whom' },
      { name: 'About', job: 'Who they are, mission, credibility' },
      { name: 'Services', job: 'What they offer' },
      { name: 'Industries', job: 'Sectors served' },
      { name: 'Testimonials', job: 'Client trust' },
      { name: 'Contact', job: 'Get in touch / enquire' },
    ],
    primaryCta: { label: 'Get in Touch', action: '#contact' },
    secondaryCta: { label: 'Our Services', action: '#services' },
    features: ['Services', 'About', 'Industries', 'Testimonials', 'Enquiry form'],
    seo: { titlePattern: '{name} — {tagline}', focus: 'company + service + industry' },
    antiPatterns: ['No personal-portfolio voice', 'No reservation/menu CTAs', 'Never generic template feel'],
  },

  // ── Personal Brands ────────────────────────────────────────
  {
    type: 'PERSONAL_PORTFOLIO',
    label: 'Personal Portfolio',
    category: 'Personal Brand',
    typePhrases: ['personal portfolio', 'portfolio', 'personal website', 'resume website', 'cv website', 'about me site'],
    strong: ['portfolio', 'resume', 'cv', 'my work', 'about me', 'hire me'],
    weak: ['projects', 'experience', 'skills', 'case study', 'freelance', 'personal'],
    design: {
      direction: 'Editorial & personal — should feel like only this person', palette: ['one ink + one neutral', 'a single signature accent from the person'],
      display: 'Characterful display chosen for personality', body: 'Clean grotesk', mono: 'Mono for metadata', mood: 'Confident, intentional, human',
      motion: 'Scroll reveals, one signature moment, restraint over spectacle',
    },
    sections: [
      { name: 'Hero', job: 'Who they are in one confident line' },
      { name: 'About', job: 'An opinionated point of view' },
      { name: 'Experience', job: 'The real career arc' },
      { name: 'Projects', job: 'Prove the craft with real work' },
      { name: 'Skills', job: 'What they bring' },
      { name: 'Contact', job: 'One confident action' },
    ],
    primaryCta: { label: 'Start a Project', action: '#contact' },
    secondaryCta: { label: 'See the Work', action: '#projects' },
    features: ['Project case studies', 'Experience timeline', 'Contact / mailto'],
    seo: { titlePattern: '{name} — {role}', focus: 'name + role + specialism' },
    antiPatterns: ['No reservation/menu CTAs', 'No generic feature/pricing grids', 'Must feel like THEM, never a template'],
  },
  {
    type: 'DEVELOPER_PORTFOLIO',
    label: 'Developer Portfolio',
    category: 'Personal Brand',
    typePhrases: ['developer portfolio', 'software developer portfolio', 'engineer portfolio', 'dev portfolio'],
    strong: ['developer', 'engineer', 'github', 'software', 'coding'],
    weak: ['projects', 'stack', 'open source', 'react', 'backend', 'repositories'],
    design: {
      direction: 'Technical-credible, precise, code-as-texture', palette: ['ink or near-black', 'one technical accent', 'mono-led detail'],
      display: 'Technical grotesk', body: 'Clean sans', mono: 'Mono prominent', mood: 'Sharp, credible, minimal',
      motion: 'Crisp, restrained',
    },
    sections: [
      { name: 'Hero', job: 'What they build, with confidence' },
      { name: 'About', job: 'How they think and work' },
      { name: 'Projects', job: 'Real shipped work + repos' },
      { name: 'Skills', job: 'Stack and strengths' },
      { name: 'Experience', job: 'Where they’ve built' },
      { name: 'Contact', job: 'Get in touch / GitHub' },
    ],
    primaryCta: { label: 'Get in Touch', action: '#contact' },
    secondaryCta: { label: 'View GitHub', action: '#projects' },
    features: ['Project case studies', 'GitHub links', 'Skills', 'Experience'],
    seo: { titlePattern: '{name} — Software Engineer', focus: 'name + stack + role' },
    antiPatterns: ['No corporate stock', 'No decorative filler', 'Never hype over substance'],
  },
  // ── Religious & Non-profit ─────────────────────────────────
  {
    type: 'NGO',
    label: 'NGO / Non-profit',
    category: 'Religious & Non-profit',
    typePhrases: ['ngo', 'non-profit', 'nonprofit', 'charity', 'foundation', 'trust'],
    strong: ['ngo', 'donate', 'mission', 'cause', 'volunteers', 'impact'],
    weak: ['programs', 'stories', 'fundraising', 'community', 'beneficiaries', 'csr'],
    design: {
      direction: 'Human, hopeful, story-led — impact you can feel', palette: ['warm hopeful base', 'one cause colour', 'photography-forward'],
      display: 'Warm humanist', body: 'Legible sans', mood: 'Compassionate, sincere, urgent-but-hopeful', motion: 'Gentle, story-driven',
    },
    sections: [
      { name: 'Hero', job: 'The cause, in a human frame' },
      { name: 'Mission', job: 'What they’re changing and why' },
      { name: 'Programs', job: 'How they create change' },
      { name: 'Impact', job: 'Numbers and outcomes' },
      { name: 'Stories', job: 'Real people, real change' },
      { name: 'Donate', job: 'Convert empathy to support' },
      { name: 'Contact', job: 'Volunteer / reach out' },
    ],
    primaryCta: { label: 'Donate Now', action: '#donate' },
    secondaryCta: { label: 'Become a Volunteer', action: '#contact' },
    features: ['Donation CTA', 'Impact numbers', 'Story features', 'Volunteer form'],
    seo: { titlePattern: '{name} — {cause} NGO in India', focus: 'cause + donate + city' },
    antiPatterns: ['No corporate coldness', 'Never exploit imagery', 'Never bury the donate action'],
  },
  {
    type: 'TEMPLE',
    label: 'Temple / Religious',
    category: 'Religious & Non-profit',
    typePhrases: ['temple', 'mandir', 'religious trust', 'shrine', 'gurudwara', 'ashram'],
    strong: ['temple', 'mandir', 'darshan', 'deity', 'puja'],
    weak: ['timings', 'aarti', 'festivals', 'donations', 'sevas', 'pilgrimage'],
    design: {
      direction: 'Reverent, warm, heritage-rooted', palette: ['saffron/maroon', 'gold', 'ivory'],
      display: 'Traditional-leaning serif', body: 'Legible sans', mood: 'Sacred, welcoming, serene', motion: 'Calm, gentle',
    },
    sections: [
      { name: 'Hero', job: 'The temple in a serene, reverent frame' },
      { name: 'About', job: 'History and significance' },
      { name: 'Darshan & Timings', job: 'Aarti and visiting hours' },
      { name: 'Events', job: 'Festivals and sevas' },
      { name: 'Gallery', job: 'The temple and celebrations' },
      { name: 'Donations', job: 'Support and seva' },
      { name: 'Contact', job: 'Reach and directions' },
    ],
    primaryCta: { label: 'Offer Donation', action: '#donations' },
    secondaryCta: { label: 'Darshan Timings', action: '#darshan-timings' },
    features: ['Timings', 'Festival calendar', 'Donations', 'Directions'],
    seo: { titlePattern: '{name} — Temple in {city}', focus: 'temple + deity + city + timings' },
    antiPatterns: ['No trendy/corporate aesthetics', 'Never irreverent imagery'],
  },
]
